#!/usr/bin/python3

import argparse
import datetime
import email
import glob
import gzip
import io
import json
import mailbox
import os
import shutil
import sys
import zipfile

import dateutil.tz
import xmltodict

try:
    import MySQLdb
except ModuleNotFoundError:
    # okay if we do not use sql mode
    pass

cc = 0

count = {}

fcount = {}
tcount = {}

failmsg = {"disposition": "", "dkim": "", "spf": ""}
warnmsg = ""

policies = ["dkim", "spf"]


def ts2local(ts):
    ts = int(ts)
    return datetime.datetime.fromtimestamp(ts, dateutil.tz.tzlocal())


def xadd(xtype, dfrom, org, n=1):
    if xtype not in fcount:
        fcount[xtype] = {}
    if dfrom not in fcount[xtype]:
        fcount[xtype][dfrom] = 0

    fcount[xtype][dfrom] += n

    if xtype not in tcount:
        tcount[xtype] = {}
    if org not in tcount[xtype]:
        tcount[xtype][org] = 0

    tcount[xtype][org] += n

    if xtype not in count:
        count[xtype] = 0
    count[xtype] += n


def tlsrptparse(indata):
    j = json.loads(indata)
    for p in j["policies"]:
        if p["summary"]["total-successful-session-count"] > 0:
            xadd(
                "tlsrpt_good",
                p["policy"]["policy-domain"],
                j["organization-name"],
                p["summary"]["total-successful-session-count"],
            )
        if p["summary"]["total-failure-session-count"] > 0:
            xadd(
                "tlsrpt_good",
                p["policy"]["policy-domain"],
                j["organization-name"],
                p["summary"]["total-failure-session-count"],
            )


def esc(instr):
    return MySQLdb._mysql.escape_string(instr).decode()


def dmarc(indata, fmail, sqlmode):
    global dkimfailmsg, spffailmsg, dispositionfailmsg, cc

    cc += 1
    if args.sql:
        with open(f"reports/{cc}", "wb") as f:
            f.write(indata)

    j = xmltodict.parse(indata)
    if "record" not in j["feedback"]:
        return
    recs = j["feedback"]["record"]
    if isinstance(recs, dict):
        recs = [recs]

    org = j["feedback"]["report_metadata"]["org_name"]
    begin = ts2local(j["feedback"]["report_metadata"]["date_range"]["begin"])
    end = ts2local(j["feedback"]["report_metadata"]["date_range"]["end"])

    for r in recs:
        rows = r["row"]

        if isinstance(rows, dict):
            rows = [rows]

        for row in rows:
            pol = row["policy_evaluated"]
            for x in policies:
                xadd(f"{x}_{pol[x]}", r["identifiers"]["header_from"], org)

            msg = ""
            if pol["spf"] != "pass":
                msg = f"SPF did not pass ({pol['spf']}) from {org}\n"
                mtype = "spf"
            if pol["dkim"] != "pass":
                msg = f"DKIM did not pass ({pol['dkim']}) from {org}\n" + msg
                mtype = "dkim"
            if pol["disposition"] != "none":
                msg = f"Disposition {pol['disposition']} from {org}\n" + msg
                mtype = "disposition"
            if msg:
                msg += f"Timeframe {begin} - {end}\n{fmail}: {r}\n\n"
                failmsg[mtype] += msg

            mailto = ""
            if "envelope_to" in r["identifiers"]:
                mailto = r["identifiers"]["envelope_to"]
            mailfrom = ""
            if "header_from" in r["identifiers"]:
                mailfrom = r["identifiers"]["header_from"]

            if sqlmode:
                print(f"INSERT INTO rua (org,mfrom,mto,dkim,spf,disposition,count,start,end,report)"
                      f" VALUES ('{esc(org)}','{esc(mailfrom)}','{esc(mailto)}',"
                      f"'{esc(pol['dkim'])}','{esc(pol['spf'])}','{esc(pol['disposition'])}',"
                      f"{esc(row['count'])},'{esc(str(begin)[0:-6])}','{esc(str(end)[0:-6])}',"
                      f"{cc});")


def parser(filename, indata, fmail, sqlmode):
    global warnmsg
    if filename.endswith(".json"):
        if sqlmode:  # does not support TLSRPT
            return
        # this is tls rpt
        tlsrptparse(indata)

    if filename.endswith(".xml"):
        # this is dmarc
        try:
            dmarc(indata, fmail, sqlmode)
        except KeyError as e:
            warnmsg += f"Incorrect reporting format in {filename}, key {e}\n"


ap = argparse.ArgumentParser()
ap.add_argument("dirs", nargs="+", help="Path to maildirs to check")
ap.add_argument("-v", "--verbose", action="store_true", help="show also good results")
ap.add_argument("-a,", "--archive", help="Dir to store archived versions")
ap.add_argument("-p", "--policies", help="DMARC policies to show (default: dkim,spf)")
ap.add_argument("-s", "--sql", action="store_true", help="SQL Mode (saves reports in reports/)")
args = ap.parse_args()

if args.policies:
    policies = args.policies.split(",")

if args.archive:
    now = datetime.datetime.now(tz=dateutil.tz.tzlocal())
    now = now.isoformat(timespec="minutes")
    nowdir = f"{args.archive}/{now}"

if args.sql:
    os.mkdir("reports")

for mdir in args.dirs:
    for d in ["cur", "new", "tmp"]:
        if not os.path.isdir(f"{mdir}/{d}"):
            sys.exit(f"Error: {mdir} not a maildir")
    for fmail in glob.glob(f"{mdir}/cur/*") + glob.glob(f"{mdir}/new/*"):
        with open(fmail, "rb") as f:
            e = email.message_from_binary_file(f)
            dparts = 0
            for part in e.walk():
                ct = part.get_content_type()
                fn = part.get_filename()
                if not isinstance(fn, str):
                    continue
                if fn.endswith(".gz"):
                    if fn.endswith(".gz"):
                        fn = fn[0:-3]
                    data = gzip.decompress(part.get_payload(decode=True))
                    dparts += 1
                    parser(fn, data, fmail, args.sql)

                if ct == "application/zip":
                    bdata = part.get_payload(decode=True)
                    ifo = io.BytesIO(bdata)
                    with zipfile.ZipFile(ifo) as fzip:
                        for x in fzip.namelist():
                            data = fzip.read(x)
                            dparts += 1
                            parser(x, data, fmail, args.sql)
            if dparts == 0:
                warnmsg += f"WARNING: No data found in {fmail}\n"
            if dparts > 1:
                warnmsg += f"WARNING: {dparts} files found, expected 1\n"
        if args.archive:
            if not os.path.isdir(nowdir):
                mailbox.Maildir(nowdir, create=True)
            shutil.move(fmail, f"{nowdir}/cur")

if count and not args.sql:
    if failmsg["disposition"] != "":
        print("WARNINGS disposition:")
        print(failmsg["disposition"], end="")
    print("All:")
    print(json.dumps(dict(sorted(count.items())), indent=2))
    print()
    print("Grouped by from domain:")
    print(json.dumps(dict(sorted(fcount.items())), indent=2))
    print()
    print("Grouped by reporting org:")
    print(json.dumps(dict(sorted(tcount.items())), indent=2))
    print()
    print(warnmsg)
    print()
    print(failmsg["dkim"], end="")
    print(failmsg["spf"], end="")
